GROUP_FOLDER = '/groups/'
ATTENDANCE_FOLDER = '/att/'
SPREADSHEET_FOLDER = '/spreadsheets/'
METADATA_FOLDER = '/metadata/'
CLASSES_FOLDER = '/classes/'
OPTIONS = ['U', 'O', 'N', 'S']
ATTENDANCE_COLUMN_NAME = 'attendence'
NAME_COLUMN_NAME = 'name'
CLASS_DATES_COLUMN_NAME = 'Class Dates'
CLASS_TITLE_COLUMN_NAME = {1: 'Class Title 1', 2: 'Class Title 2'}
DOCUMENTS_FOLDER = '/private/var/mobile/Containers/Data/Application/EC803869-F9F4-4BC3-8182-AEF407918EFA/Documents/'
